name: 'label PRs'
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: label PRs
        uses: actions/labeler@v5
        with:
          configuration-path: .github/pr_labels.yml
